# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

run:
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats: {text: {path: stdout}}

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - nestif
    - nlreturn
    - nolintlint
    - prealloc
    - promlinter
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - wsl
  settings:
    dupl:
      threshold: 100
    forbidigo:
      forbid:
        - pattern: ^(fmt\.Print(|f|ln)|print(|ln))(# it looks like a forgotten debugging printing call)?$
    goconst:
      min-len: 2
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    godot:
      scope: declarations
      capital: false
    govet:
      enable:
        - shadow
    lll:
      line-length: 120
    misspell:
      locale: US
      ignore-rules:
        - cancelled
    nakedret:
      max-func-lines: 100
    nolintlint:
      require-specific: true
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - gochecknoglobals
          - gocognit
          - scopelint
        path: _test\.go
    paths:
      - .github
      - .git
      - tmp
      - temp
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(gh.tarampamp.am/webhook-tester)
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - .github
      - .git
      - tmp
      - temp
      - third_party$
      - builtin$
      - examples$
